<?php

$adminConfig['userGroupNum']=4; // Number of user groups, to be displayed
$adminConfig['htmlCharset']="utf-8"; // Leave it blank, if you do not want to use one
$adminConfig['htmlCss']="default.css"; // Leave it blank, if you do not want to use one
$adminConfig['htmlTitle']="My Book"; // HTML Title
$adminConfig['pageTitle']="My Book";
$adminConfig['curUserMsg']="Έχετε συνδεθεί ως χρήστης: ";
$adminConfig['allAdminMsg']="Αριθμός των εγγεγραμμένων administrators: ";
$adminConfig['allUserMsg']="Αριθμός των εγγεγραμμένων normal users: ";
$adminConfig['selectMsg']="Επιλέξτε έναν χρήστη για διαμόρφωση: ";
$adminConfig['editBtn']="Διαμόρφωση";
$adminConfig['newBtn']="Προσθήκη νέου Χρήστη";
$adminConfig['tableBtn']="Λίστα Χρηστών";
$adminConfig['logoutBtn']="Logout";
$adminConfig['cancelBtn']="Cancel";
$adminConfig['submitBtn']="Υποβολή";
$adminConfig['resetBtn']="Reset";
$adminConfig['deleteBtn']="Διαγραφή Χρήστη";
$adminConfig['okBtn']="OK";
$adminConfig['editUserMsg']=" Επιλέξατε τον παρακάτω χρήστη για αλλαγή: ";
$adminConfig['editInfoMsg']="Αν δεν θέλετε να αλλάξετε τον κωδικό, αφήστε κενό το πεδίο.";
$adminConfig['editPassMsg']="Password: ";
$adminConfig['editIsAdminMsg']="Administrator: ";
$adminConfig['editUserGroupMsg']="Ομάδα: ";
$adminConfig['editYes']="YES";
$adminConfig['editNo']="NO";
$adminConfig['editRemarkMsg']="Σχόλια: ";
$adminConfig['editUpdMsg']="Ο παρακάτω χρήστης ανανεώθηκε: ";
$adminConfig['delConfirmMsg']="Να διαγραφεί ο παρακάτω χρήστης: ";
$adminConfig['delDelMsg']="Ο παρακάτω χρήστης διαγράφηκε ";
$adminConfig['delNotDelMsg']="Δεν έγινε η διαγραφή του παρακάτω χρήστη: ";
$adminConfig['newUserMsg']="Email: ";
$adminConfig['newPassMsg']="Password: ";
$adminConfig['newIsAdminMsg']="Administrator: ";
$adminConfig['newUserMsgfirst']="Παρακαλώ εισάγετε νέο χρήστη ";
$adminConfig['newUserGroupMsg']="Ομάδα Χρήστη: ";
$adminConfig['newYes']="YES";
$adminConfig['newNo']="NO";
$adminConfig['newRemarkMsg']="Remarks: ";
$adminConfig['newAddedMsg']="The following user has been added: ";
$adminConfig['newExistsMsg']="The following user already exists: ";
$adminConfig['newNoUserMsg']="No username was given. Please try again!";
$adminConfig['newNoPassMsg']="No password was given. Please try again!";
$adminConfig['newNoUserPassMsg']="No username and no password was given. Please try again!";
?>